# This is a basic workflow to help you get started with Actions

name: Publishing package to pypi with minor change.

# Controls when the workflow will run
on: 
  pull_request:
    types: [closed]
    branches: 
      - main

jobs:
  publish_minor:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup up python
        id: setup-python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Bump version
        run: poetry version minor
      - name: push version increase
        run: |
          git pull
          git add pyproject.toml
          git add poetry.lock
          git config --global user.name 'GitHub Actions'
          git config --global user.name 'maxspahn@users.noreply.github.com'
          git commit -m "Bumps version number."
          git push
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.13
        with:
          python_version: "3.8"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
